#! /bin/sh

all: FENtranslator NEURAL_NET MASTER_AI NEURAL_NET_COMPARISON

FENtranslator: FENtranslator.o
	gcc FENtranslator.o -o FENtranslator

NEURAL_NET: NEURAL_NET.o NEURAL_NET_COMPARISON.o
	gcc NEURAL_NET.o NEURAL_NET_COMPARISON.o -o NEURAL_NET

MASTER_AI: MASTER_AI.o
	gcc MASTER_AI.o -o MASTER_AI
	
FENtranslator.o: FENtranslator.c
	gcc -c FENtranslator.c

NEURAL_NET.o: NEURAL_NET.c
	gcc -c NEURAL_NET.c

MASTER_AI.o: MASTER_AI.c
	gcc -c MASTER_AI.c

NEURAL_NET_COMPARISON.o: NEURAL_NET_COMPARISON.c
	gcc -c NEURAL_NET_COMPARISON.c

clean:
	rm FENtranslator FENtranslator.o NEURAL_NET NEURAL_NET.o MASTER_AI MASTER_AI.o NEURAL_NET_COMPARISON NEURAL_NET_COMPARISON.o
